app:
    host: localhost
    port: 8080
    logger_level: "DEBUG"
    request_time: 10s
    search_duration: 5m

database:
    host: localhost
    port: 6379
    user: ""
    password: ""
    database: 1

broker:
    host: localhost
    port: 5672
    user: example_user
    password: example_password
    queue: searches_queue
